spring:
  application:
    name: spring-testing
  datasource:
    url: jdbc:h2:file:./db/person-db
    username: bxiit
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update